on: [push]

name: swagger-validation
jobs:
  validate_errors:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote - errors
    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        with:
          definition-file: src/errors.json

  validate_about:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote - about
    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        with:
          definition-file: src/about.json
